import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'id' | 'ja' | 'fil' | 'pt' | 'tr' | 'ko' | 'ru' | 'zh';

export interface LanguageInfo {
  code: LanguageCode;
  name: string;
  flag: string;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'id', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'fil', name: 'Filipino', flag: '🇵🇭' },
  { code: 'pt', name: 'Português (BR)', flag: '🇧🇷' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷' },
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'zh', name: '简体中文', flag: '🇨🇳' }
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    TOOL_VALORANT: 'Valorant Tools',
    AIM_SETTINGS: 'Aim & Settings',
    AIM_TRAINER: 'Aim Trainer',
    PROFILE: 'Profile',
    CROSSHAIR_BUILDER: 'Crosshair Builder',
    SENS_CONVERTER: 'Sens Converter',
    SENS_FINDER: 'Sens Finder (PSA)',
    TACTICAL_TIER_LIST: 'Tactical Tier List',
    DRAFT_SIMULATOR: 'Draft Simulator',
    ARMORY_HUB: 'Collection',
    STRATEGY_BOARD: 'Strategy Board',
    TACTICAL_ANALYST_PLATFORM: 'TACTICAL ANALYST PLATFORM',
    SELECT_MAP_PLAN: 'Select Map to Plan Strategy',
    SEARCH_MAP: 'Search map...',
    ACTIVE_MAPS: 'Active Maps',
    CUSTOM_MAPS: 'Custom Maps',
    ALL_MAPS: 'All Maps',
    SIGN_IN_REGISTER: 'Sign In / Register',
    LOG_OUT: 'Log Out',
    BACK_TO_HOME: 'Back to Home',
    SWAP_SIDES: 'Swap Sides',
    RESET_ALL: 'Reset All',
    SIMULATE: 'Simulate 10,000x',
    SIMULATING: 'Simulating...',
    SELECT_MAP: 'Select Map',
    SKILL_BRACKET: 'Skill Bracket',
    MATCH_ANALYST_FORECAST: 'Monte Carlo Match Outcome Forecast Engine',
    ACTIVE_COMBAT_ZONE: 'Active Combat Zone',
    MATCH_ANALYSIS_PROJECTION: 'Match Analysis Projection',
    PROYEKSI_ANALISIS: 'Match Analysis Projection',
    DETAILED_DUAL_SIDE_ANALYSIS: 'Detailed Dual-Side Analysis',
    EVALUASI_FASE_MENYERANG: 'Attacker Phase Evaluation',
    EVALUASI_FASE_BERTAHAN: 'Defender Phase Evaluation',
    TEAM_A_ATTACKING: 'Team A Attacking',
    TEAM_B_ATTACKING: 'Team B Attacking',
    TEAM_A_DEFENDING: 'Team A Defending',
    TEAM_B_DEFENDING: 'Team B Defending',
    LIHAT_EVALUASI_TAKTIS: 'See Tactical Evaluation',
    AUTO_RECOMMENDATION_ENGINE: 'Auto Recommendation Engine',
    ROLE_BALANCE_CHECK: 'Role Balance Check',
    DETECTED_SYNERGIES: 'Detected Synergies',
    COUNTERED_BY_OPPONENT: 'Countered by Opponent',
    
    // NEW DETAILED TRANSLATIONS
    CHOOSE_5_AGENTS: 'Select 5 Agents for each team and run the match simulation.',
    REC_ENGINE_BANNER: 'AUTO RECOMMENDATION ENGINE',
    REC_INPUT_SMOKE: 'Input Smoke / Controller to complete the strategic base.',
    REC_GANTI: 'REPLACE',
    REC_RECOMMENDED_INPUT: 'RECOMMENDED INPUT',
    REC_DRAFT: 'DRAFT',
    EMPTY: 'EMPTY',
    HAPUS: 'Remove',
    SCAN_STEP1: 'EVALUATING ROLE COMPOSITION DATA...',
    SCAN_STEP2: 'ANALYZING SYNERGIES & COUNTER-PICKS...',
    SCAN_STEP3: 'CALCULATING 10,000 MATRIX DISTRIBUTIONS...',
    SCAN_STEP4: 'SIMULATING MATCH SCENARIOS...',
    VERDICT_TITLE_STRENGTH: 'MAIN STRENGTH OF {team}',
    VERDICT_TITLE_WEAKNESS: 'MAIN WEAKNESS OF {team}',
    VERDICT_CASE1_ATTACKER: 'Team A is projected to struggle due to having no Sentinel to secure post-plant holds. Even if Team A takes a site, they will be extremely vulnerable to a clean retake from Team B\'s layered defense.',
    VERDICT_CASE1_DEFENDER: 'Team B is favored due to having {agents} acting as solid site anchors. This allows Team B to delay entries and execute coordinated retakes.',
    VERDICT_CASE2_ATTACKER: 'Team A is favored due to high initiation flexibility. With a balanced draft, Team A can easily bait out Team B\'s defensive utility before executing a massive site take.',
    VERDICT_CASE2_DEFENDER: 'Team B is projected to lag behind due to an overly aggressive defensive draft (Double Duelist). Without solid passive site anchors on map {map}, Team B will easily be baited out and dictated by Team A\'s tactical rotations.',
    VERDICT_CASE3_FAVORED: 'Team {favored} is favored purely due to significantly higher individual map mastery. The average base win rate of Team {favored}\'s selected agents on {map} vastly outperforms Team {lagging}\'s baseline on {rank}.',
    VERDICT_CASE3_LAGGING: 'Team {lagging} is projected to lag behind because the average base win rate of the selected agents on {map} is less optimal compared to Team {favored}\'s draft composition on {rank}.',
    SIDE_ANALYSIS_EMPTY: 'No Agents selected for {team} yet.',
    SIDE_ANALYSIS_ATTACK_STRONG: 'With execution combinations from <span class="text-[#F4D35E] font-bold">{agents}</span>, your team has a very high entry explosion on the attack phase on map <span class="text-[#F4D35E] font-bold">{map}</span>. Your initiation is extremely strong to push back enemy defenses.',
    SIDE_ANALYSIS_ATTACK_WEAK: 'Your team is projected to hit a wall on the attack phase due to having no <span class="text-[#F4D35E] font-bold">Initiator</span> to gather early information. You will be forced into blind 1v1 duels without zone detection.',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'Your team has a measured attacking pace with proportional tactical initiations on map <span class="text-[#F4D35E] font-bold">{map}</span>, allowing coordinates to clear site angles progressively.',
    SIDE_ANALYSIS_DEFEND_STRONG: 'Your defensive phase is very solid thanks to the presence of <span class="text-[#F4D35E] font-bold">{agents}</span>. You have excellent entry delay and choke-point denial capabilities, forcing attackers to waste time or rotate.',
    SIDE_ANALYSIS_DEFEND_WEAK: 'Your static defense is highly fragile due to having no anchor <span class="text-[#F4D35E] font-bold">Sentinel</span> on map <span class="text-[#F4D35E] font-bold">{map}</span>. You will be forced to play deep off-site and rely heavily on high-risk retakes.',
    MICRO_REC_ROLE_GAP: 'Your team composition currently has no {role}. Replacing {oldAgent} with {newAgent} is crucial to deny enemy sightlines on map {map} and boost win rates by +{winrate}%.',
    MICRO_REC_DOUBLE_DUELIST: 'Team B is currently running an overly aggressive composition (Double Duelist) for defenders on map {map}. Replacing {oldAgent} with {newAgent} (Sentinel) will secure a much sturdier site anchor to stop enemy penetration.',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent} has suboptimal performance statistics on map {map} at rank {rank}. Replacing with {newAgent} provides more consistent utility efficiency, increasing the projection simulation by +{winrate}%.',
    MICRO_REC_EMPTY_SLOT: 'Filling the empty slot with {newAgent} provides more consistent utility efficiency on map {map} at rank {rank}, increasing the projection simulation by +{winrate}%.',
    CHOOSE_MAP: 'Choose Map',
    RANK_LOW: 'Iron - Silver',
    RANK_MID: 'Gold - Platinum',
    RANK_HIGH: 'Diamond - Radiant',
    SEARCH_AGENT_PLACEHOLDER: 'Search agent...',
    SELECT_AGENT_FOR_TEAM: 'SELECT AGENT FOR {team} (SLOT {slot})',
    CLOSE: 'Close',
    SEARCH_AGENT: 'Search agent...'
  },
  id: {
    TOOL_VALORANT: 'Tool Valorant',
    AIM_SETTINGS: 'Aim & Pengaturan',
    AIM_TRAINER: 'Latihan Membidik',
    PROFILE: 'Profil',
    CROSSHAIR_BUILDER: 'Pembuat Crosshair',
    SENS_CONVERTER: 'Konverter Sens',
    SENS_FINDER: 'Pencari Sens (PSA)',
    TACTICAL_TIER_LIST: 'Peringkat Taktis',
    DRAFT_SIMULATOR: 'Simulator Draft',
    ARMORY_HUB: 'Koleksi',
    STRATEGY_BOARD: 'Papan Strategi',
    TACTICAL_ANALYST_PLATFORM: 'PLATFORM ANALIS TAKTIS',
    SELECT_MAP_PLAN: 'Pilih Peta untuk Merancang Strategi',
    SEARCH_MAP: 'Cari peta...',
    ACTIVE_MAPS: 'Peta Aktif',
    CUSTOM_MAPS: 'Peta Kustom',
    ALL_MAPS: 'Semua Peta',
    SIGN_IN_REGISTER: 'Masuk / Daftar',
    LOG_OUT: 'Keluar',
    BACK_TO_HOME: 'Kembali ke Beranda',
    SWAP_SIDES: 'Tukar Side',
    RESET_ALL: 'Reset Semua',
    SIMULATE: 'Simulasi 10.000x',
    SIMULATING: 'Menyimulasikan...',
    SELECT_MAP: 'Pilih Peta',
    SKILL_BRACKET: 'Braket Kemampuan',
    MATCH_ANALYST_FORECAST: 'Mesin Prediksi Hasil Pertandingan Monte Carlo',
    ACTIVE_COMBAT_ZONE: 'Zona Tempur Aktif',
    MATCH_ANALYSIS_PROJECTION: 'Proyeksi Analisis Pertandingan',
    PROYEKSI_ANALISIS: 'Proyeksi Analisis Pertandingan',
    DETAILED_DUAL_SIDE_ANALYSIS: 'Analisis Detail Dua Sisi',
    EVALUASI_FASE_MENYERANG: 'Evaluasi Fase Menyerang (Attacker Phase)',
    EVALUASI_FASE_BERTAHAN: 'Evaluasi Fase Bertahan (Defender Phase)',
    TEAM_A_ATTACKING: 'Team A Menyerang',
    TEAM_B_ATTACKING: 'Team B Menyerang',
    TEAM_A_DEFENDING: 'Team A Bertahan',
    TEAM_B_DEFENDING: 'Team B Bertahan',
    LIHAT_EVALUASI_TAKTIS: 'Lihat Evaluasi Taktis',
    AUTO_RECOMMENDATION_ENGINE: 'Mesin Rekomendasi Otomatis',
    ROLE_BALANCE_CHECK: 'Pemeriksaan Keseimbangan Peran',
    DETECTED_SYNERGIES: 'Sinergi Terdeteksi',
    COUNTERED_BY_OPPONENT: 'Di-counter oleh Lawan',
    
    CHOOSE_5_AGENTS: 'Pilih 5 Agent untuk masing-masing tim dan jalankan simulasi hasil pertandingan.',
    REC_ENGINE_BANNER: 'MESIN REKOMENDASI OTOMATIS',
    REC_INPUT_SMOKE: 'Masukan Smoke / Controller untuk mengisi basis strategi.',
    REC_GANTI: 'GANTI',
    REC_RECOMMENDED_INPUT: 'REKOMENDASI INPUT',
    REC_DRAFT: 'DRAFT',
    EMPTY: 'KOSONG',
    HAPUS: 'Hapus',
    SCAN_STEP1: 'MENGEVALUASI DATA KOMPOSISI PERAN...',
    SCAN_STEP2: 'MENGANALISIS SINERGI DAN COUNTER-PICKS...',
    SCAN_STEP3: 'MENGKALKULASI 10.000 DISTRIBUSI MATRIKS...',
    SCAN_STEP4: 'MENSIMULASIKAN SKENARIO PERTANDINGAN...',
    VERDICT_TITLE_STRENGTH: 'KEUNGGULAN UTAMA {team}',
    VERDICT_TITLE_WEAKNESS: 'KELEMAHAN UTAMA {team}',
    VERDICT_CASE1_ATTACKER: 'Team A diproyeksikan kesulitan karena tidak memiliki Sentinel untuk menahan taktik pasca-pemasangan (*post-plant hold*). Meskipun Team A berhasil menembus site, mereka akan sangat rentan terkena sapuan bersih (*retake*) dari pertahanan berlapis Team B.',
    VERDICT_CASE1_DEFENDER: 'Team B diunggulkan karena memiliki {agents} yang bertindak sebagai jangkar pertahanan kokoh. Hal ini memungkinkan Team B melakukan penundaan (*delay*) serangan dan melakukan eksekusi *retake* yang sangat rapi.',
    VERDICT_CASE2_ATTACKER: 'Team A diunggulkan karena memiliki fleksibilitas inisiasi yang tinggi. Dengan draf yang seimbang, Team A dapat dengan mudah memancing utilitas pertahanan Team B keluar sebelum melakukan eksekusi site secara masif.',
    VERDICT_CASE2_DEFENDER: 'Team B diproyeksikan tertinggal karena draf pertahanan yang terlalu agresif (Double Duelist). Tanpa pertahanan pasif yang kokoh di map {map}, Team B akan mudah terpancing keluar dan didikte oleh rotasi taktis Team A.',
    VERDICT_CASE3_FAVORED: 'Team {favored} diunggulkan murni karena penguasaan peta (*map mastery*) individu yang jauh lebih tinggi. Rata-rata tingkat kemenangan dasar Agent pilihan Team {favored} di map {map} jauh melampaui statistik dasar Team {lagging} pada rank {rank}.',
    VERDICT_CASE3_LAGGING: 'Team {lagging} diproyeksikan tertinggal karena rata-rata tingkat kemenangan dasar Agent pilihan di map {map} kurang optimal dibandingkan komposisi Team {favored} pada rank {rank}.',
    SIDE_ANALYSIS_EMPTY: 'Belum ada Agent yang dipilih untuk {team}.',
    SIDE_ANALYSIS_ATTACK_STRONG: 'Dengan kombinasi eksekusi dari <span class="text-[#F4D35E] font-bold">{agents}</span>, Team Anda memiliki daya dobrak masuk site (<span class="text-[#F4D35E] font-bold">*entry explosion*</span>) yang sangat tinggi pada fase menyerang di map <span class="text-[#F4D35E] font-bold">{map}</span>. Inisiasi awal Anda sangat kuat untuk memaksa pertahanan musuh mundur.',
    SIDE_ANALYSIS_ATTACK_WEAK: 'Team Anda diproyeksikan mengalami kebuntuan saat menyerang karena tidak adanya <span class="text-[#F4D35E] font-bold">Initiator</span> untuk mencari informasi awal. Anda akan dipaksa melakukan duel satu-lawan-satu secara buta tanpa adanya deteksi area terlebih dahulu.',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'Team Anda memiliki tempo penyerangan yang terukur dengan inisiasi taktis yang proporsional di map <span class="text-[#F4D35E] font-bold">{map}</span>, memungkinkan koordinasi pembersihan sudut site secara bertahap.',
    SIDE_ANALYSIS_DEFEND_STRONG: 'Fase bertahan Anda sangat kokoh berkat kehadiran <span class="text-[#F4D35E] font-bold">{agents}</span>. Anda memiliki kemampuan penundaan (<span class="text-[#F4D35E] font-bold">*delay*</span>) dan penutupan jalur masuk yang luar biasa, memaksa penyerang membuang banyak waktu atau berputar arah.',
    SIDE_ANALYSIS_DEFEND_WEAK: 'Pertahanan statis Anda sangat rapuh karena ketiadaan <span class="text-[#F4D35E] font-bold">Sentinel</span> jangkar di map <span class="text-[#F4D35E] font-bold">{map}</span>. Anda akan dipaksa bermain defensif jauh di belakang site dan sangat bergantung pada koordinasi serangan balik (<span class="text-[#F4D35E] font-bold">*retake*</span>) yang berisiko tinggi.',
    MICRO_REC_ROLE_GAP: 'Komposisi tim Anda saat ini tidak memiliki {role}. Mengganti {oldAgent} dengan {newAgent} sangat krusial untuk menutup sudut pandang musuh di map {map} dan menaikkan peluang kemenangan tim Anda sebesar +{winrate}%.',
    MICRO_REC_DOUBLE_DUELIST: 'Team B saat ini menggunakan komposisi terlalu agresif (Double Duelist) untuk posisi Defender di map {map}. Mengganti {oldAgent} dengan {newAgent} (Sentinel) akan memberikan pertahanan jangkar (*site anchor*) yang jauh lebih kokoh menghadapi penetrasi musuh.',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent} memiliki statistik performa yang kurang optimal di map {map} pada rank {rank}. Menggantinya dengan {newAgent} memberikan efisiensi utilitas yang lebih konsisten, meningkatkan proyeksi simulasi sebesar +{winrate}%.',
    MICRO_REC_EMPTY_SLOT: 'Mengisi slot kosong dengan {newAgent} memberikan efisiensi utilitas yang lebih konsisten di map {map} pada rank {rank}, meningkatkan proyeksi simulasi sebesar +{winrate}%.',
    CHOOSE_MAP: 'Pilih Map',
    RANK_LOW: 'Iron - Silver',
    RANK_MID: 'Gold - Platinum',
    RANK_HIGH: 'Diamond - Radiant',
    SEARCH_AGENT_PLACEHOLDER: 'Cari agen...',
    SELECT_AGENT_FOR_TEAM: 'PILIH AGENT UNTUK {team} (SLOT {slot})',
    CLOSE: 'Tutup',
    SEARCH_AGENT: 'Cari agen...'
  },
  ja: {
    TOOL_VALORANT: 'Valorant ツール',
    AIM_SETTINGS: 'エイム & 設定',
    AIM_TRAINER: 'エイムトレーナー',
    PROFILE: 'プロフィール',
    CROSSHAIR_BUILDER: 'クロスヘアビルダー',
    SENS_CONVERTER: '感度コンバーター',
    SENS_FINDER: '感度ファインダー (PSA)',
    TACTICAL_TIER_LIST: 'タクティカルティアリスト',
    DRAFT_SIMULATOR: 'ドラフトシミュレーター',
    ARMORY_HUB: 'コレクション',
    STRATEGY_BOARD: '戦略ボード',
    TACTICAL_ANALYST_PLATFORM: 'タクティカル アナリスト プラットフォーム',
    SELECT_MAP_PLAN: '戦略を計画するマップを選択',
    SEARCH_MAP: 'マップを検索...',
    ACTIVE_MAPS: 'アクティブマップ',
    CUSTOM_MAPS: 'カスタムマップ',
    ALL_MAPS: 'すべてのマップ',
    SIGN_IN_REGISTER: 'サインイン / 登録',
    LOG_OUT: 'ログアウト',
    BACK_TO_HOME: 'ホームに戻る',
    SWAP_SIDES: 'サイド交代',
    RESET_ALL: 'すべてリセット',
    SIMULATE: '10,000回シミュレート',
    SIMULATING: 'シミュレート中...',
    SELECT_MAP: 'マップ選択',
    SKILL_BRACKET: 'スキルブラケット',
    MATCH_ANALYST_FORECAST: 'モンテカルロ試合結果予測エンジン',
    ACTIVE_COMBAT_ZONE: 'アクティブ戦闘ゾーン',
    MATCH_ANALYSIS_PROJECTION: '試合分析プロジェクション',
    PROYEKSI_ANALISIS: '試合分析予測',
    DETAILED_DUAL_SIDE_ANALYSIS: '両サイド詳細分析',
    EVALUASI_FASE_MENYERANG: 'アタッカーフェーズ評価',
    EVALUASI_FASE_BERTAHAN: 'ディフェンダーフェーズ評価',
    TEAM_A_ATTACKING: 'チームA 攻撃',
    TEAM_B_ATTACKING: 'チームB 攻撃',
    TEAM_A_DEFENDING: 'チームA 防衛',
    TEAM_B_DEFENDING: 'チームB 防衛',
    LIHAT_EVALUASI_TAKTIS: 'タクティカル評価を見る',
    AUTO_RECOMMENDATION_ENGINE: '自動推奨エンジン',
    ROLE_BALANCE_CHECK: 'ロールバランスチェック',
    DETECTED_SYNERGIES: '検出されたシナジー',
    COUNTERED_BY_OPPONENT: '敵によるカウンター',
    
    CHOOSE_5_AGENTS: '各チームから5人のエージェントを選択し、試合シミュレーションを実行します。',
    REC_ENGINE_BANNER: '自動推奨エンジン',
    REC_INPUT_SMOKE: '戦略的基盤を完了するためにスモーク/コントローラーを入力します。',
    REC_GANTI: '交代',
    REC_RECOMMENDED_INPUT: '推奨入力',
    REC_DRAFT: 'ドラフト',
    EMPTY: '空',
    HAPUS: '削除',
    SCAN_STEP1: 'ロール構成データを評価中...',
    SCAN_STEP2: 'シナジーとカウンターピックを分析中...',
    SCAN_STEP3: '10,000通りのマトリックス分布を計算中...',
    SCAN_STEP4: '試合シナリオをシミュレート中...',
    VERDICT_TITLE_STRENGTH: '{team}の主な強み',
    VERDICT_TITLE_WEAKNESS: '{team}の主な弱み',
    VERDICT_CASE1_ATTACKER: 'チームAはポストプラント（設置後）を維持するためのセンチネルがいないため、苦戦が予想されます。サイトへの侵入に成功しても、チームBの厚い守備によるリテイクに対して非常に脆弱になります。',
    VERDICT_CASE1_DEFENDER: 'チームBは、サイトアンカーとして機能する{agents}がいるため有利です。これにより侵入を遅らせ、連携のとれたリテイクを実行できます。',
    VERDICT_CASE2_ATTACKER: 'チームAはイニシエーションの柔軟性が高いため有利です。バランスの取れたドラフトにより、サイトを大きく制圧する前にチームBの防衛ユーティリティを誘い出すことができます。',
    VERDICT_CASE2_DEFENDER: 'チームBは攻撃的すぎる防衛ドラフト（ダブルデュエリスト）のため劣勢が予想されます。マップ{map}で強固なサイトアンカーがないため、チームBは誘い出されやすく、チームAの戦術的なローテーションに翻弄されるでしょう。',
    VERDICT_CASE3_FAVORED: 'チーム{favored}は、個々のマップ習熟度が著しく高いため有利です。{map}におけるチーム{favored}の選択エージェントの平均勝率は、{rank}でのチーム{lagging}の基準値を大きく上回っています。',
    VERDICT_CASE3_LAGGING: 'チーム{lagging}は、{map}における選択エージェントの平均勝率が{rank}でのチーム{favored}の構成に比べて劣るため、劣勢が予想されます。',
    SIDE_ANALYSIS_EMPTY: '{team}のエージェントがまだ選択されていません。',
    SIDE_ANALYSIS_ATTACK_STRONG: '<span class="text-[#F4D35E] font-bold">{agents}</span>によるエントリー実行の組み合わせにより、あなたのチームはマップ<span class="text-[#F4D35E] font-bold">{map}</span>での攻撃フェーズにおいて非常に高いエントリー力（<span class="text-[#F4D35E] font-bold">*entry explosion*</span>）を持ちます。敵の防衛を押し返すイニシエーションが非常に強力です。',
    SIDE_ANALYSIS_ATTACK_WEAK: '初期の情報を収集する<span class="text-[#F4D35E] font-bold">イニシエーター</span>がいないため、攻撃フェーズで行き詰まることが予想されます。エリア検出がないため、ブラインドでの1対1の撃ち合いを強いられるでしょう。',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'あなたのチームはマップ<span class="text-[#F4D35E] font-bold">{map}</span>で適切な戦術的イニシエーションを伴う、適度な攻撃ペースを持っており、サイトの角度を段階的にクリアすることができます。',
    SIDE_ANALYSIS_DEFEND_STRONG: '<span class="text-[#F4D35E] font-bold">{agents}</span>の存在により、防衛フェーズは非常に強固です。優れた侵入遅延（<span class="text-[#F4D35E] font-bold">*delay*</span>）と侵入口遮断の能力を持ち、攻撃側に時間を浪費させるかローテーションを強要させます。',
    SIDE_ANALYSIS_DEFEND_WEAK: 'マップ<span class="text-[#F4D35E] font-bold">{map}</span>において防衛アンカーとなる<span class="text-[#F4D35E] font-bold">センチネル</span>がいないため、スタティックな防衛は非常に脆弱です。サイト奥深くでの防衛を強いられ、リスクの高いリテイク（<span class="text-[#F4D35E] font-bold">*retake*</span>）の連携に大きく依存することになります。',
    MICRO_REC_ROLE_GAP: '現在のチーム構成には{role}が不足しています。マップ{map}で敵の視線を遮り、勝率を+{winrate}%向上させるために、{oldAgent}を{newAgent}に交代することが極めて重要です。',
    MICRO_REC_DOUBLE_DUELIST: 'チームBはマップ{map}での防衛において、攻撃的すぎる構成（ダブルデュエリスト）を使用しています。{oldAgent}を{newAgent}（センチネル）に交代することで、敵の突破を防ぐためのより強固なサイトアンカーが確保されます。',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent}はランク{rank}のマップ{map}において最適とは言えないパフォーマンス統計となっています。{newAgent}に交代することで、より安定したユーティリティの効率が得られ、シミュレーション予測が+{winrate}%向上します。',
    MICRO_REC_EMPTY_SLOT: '空きスロットに{newAgent}を編成することで、ランク{rank}のマップ{map}におけるユーティリティ効率が向上し、シミュレーション予測が+{winrate}%向上します。',
    CHOOSE_MAP: 'マップを選択',
    RANK_LOW: 'アイアン - シルバー',
    RANK_MID: 'ゴールド - プラチナ',
    RANK_HIGH: 'ダイヤ - レディアント',
    SEARCH_AGENT_PLACEHOLDER: 'エージェントを検索...',
    SELECT_AGENT_FOR_TEAM: '{team}のエージェントを選択 (スロット {slot})',
    CLOSE: '閉じる',
    SEARCH_AGENT: 'エージェントを検索...'
  },
  fil: {
    TOOL_VALORANT: 'Mga Tool sa Valorant',
    AIM_SETTINGS: 'Aim & Settings',
    AIM_TRAINER: 'Aim Trainer',
    PROFILE: 'Profile',
    CROSSHAIR_BUILDER: 'Tagabuo ng Crosshair',
    SENS_CONVERTER: 'Tagasalin ng Sens',
    SENS_FINDER: 'Tagapaghanap ng Sens (PSA)',
    TACTICAL_TIER_LIST: 'Talaan ng Tier',
    DRAFT_SIMULATOR: 'Draft Simulator',
    ARMORY_HUB: 'Koleksyon',
    STRATEGY_BOARD: 'Board ng Estratehiya',
    TACTICAL_ANALYST_PLATFORM: 'PLATAPORMA NG TAKTIKAL NA ANALIS',
    SELECT_MAP_PLAN: 'Pumili ng Map para sa Estratehiya',
    SEARCH_MAP: 'Maghanap ng map...',
    ACTIVE_MAPS: 'Mga Aktibong Map',
    CUSTOM_MAPS: 'Mga Custom Map',
    ALL_MAPS: 'Lahat ng Map',
    SIGN_IN_REGISTER: 'Mag-sign In / Magparehistro',
    LOG_OUT: 'Mag-log Out',
    BACK_TO_HOME: 'Bumalik sa Home',
    SWAP_SIDES: 'Magpalit ng Side',
    RESET_ALL: 'I-reset Lahat',
    SIMULATE: 'Simulahin ng 10,000x',
    SIMULATING: 'Nagsisimula...',
    SELECT_MAP: 'Pumili ng Map',
    SKILL_BRACKET: 'Bracket ng Kakayahan',
    MATCH_ANALYST_FORECAST: 'Monte Carlo Engine ng Pagtataya sa Laro',
    ACTIVE_COMBAT_ZONE: 'Aktibong Sona ng Labanan',
    MATCH_ANALYSIS_PROJECTION: 'Proyekksyon ng Pagsusuri sa Laro',
    PROYEKSI_ANALISIS: 'Proyekksyon ng Pagsusuri ng Laro',
    DETAILED_DUAL_SIDE_ANALYSIS: 'Detalyadong Pagsusuri sa Dalawang Side',
    EVALUASI_FASE_MENYERANG: 'Pagsusuri sa Parte ng Pag-atake',
    EVALUASI_FASE_BERTAHAN: 'Pagsusuri sa Parte ng Pagtatanggol',
    TEAM_A_ATTACKING: 'Pag-atake ng Team A',
    TEAM_B_ATTACKING: 'Pag-atake ng Team B',
    TEAM_A_DEFENDING: 'Pagtatanggol ng Team A',
    TEAM_B_DEFENDING: 'Pagtatanggol ng Team B',
    LIHAT_EVALUASI_TAKTIS: 'Tingnan ang Taktikal na Pagsusuri',
    AUTO_RECOMMENDATION_ENGINE: 'Engine ng Awtomatikong Rekomendasyon',
    ROLE_BALANCE_CHECK: 'Suri sa Balanse ng Role',
    DETECTED_SYNERGIES: 'Mga Nakitang Synergy',
    COUNTERED_BY_OPPONENT: 'Na-counter ng Kalaban',
    
    CHOOSE_5_AGENTS: 'Pumili ng 5 Agent para sa bawat koponan at simulan ang simulasyon ng laro.',
    REC_ENGINE_BANNER: 'ENGINE NG AWTOMATIKONG REKOMENDASYON',
    REC_INPUT_SMOKE: 'Magpasok ng Smoke / Controller para makumpleto ang estratehiya.',
    REC_GANTI: 'PALITAN',
    REC_RECOMMENDED_INPUT: 'REKOMENDADONG INPUT',
    REC_DRAFT: 'DRAFT',
    EMPTY: 'WALANG LAMAN',
    HAPUS: 'Alisin',
    SCAN_STEP1: 'TINATAYA ANG DATA NG BALANSE NG ROLE...',
    SCAN_STEP2: 'SURI NG MGA SYNERGY AT COUNTER-PICK...',
    SCAN_STEP3: 'KUMAKALKULA NG 10,000 DISTRIBUSYON NG MATRIX...',
    SCAN_STEP4: 'NAGSISIMULA NG MGA SCENARIO NG LARO...',
    VERDICT_TITLE_STRENGTH: 'PANGUNAHING KALAKASAN NG {team}',
    VERDICT_TITLE_WEAKNESS: 'PANGUNAHING KAHINAAN NG {team}',
    VERDICT_CASE1_ATTACKER: 'Ang Team A ay inaasahang mahihirapan dahil walang Sentinel para sa post-plant hold. Kahit makapasok sila sa site, mahina pa rin sila sa mabilis na retake ng Team B.',
    VERDICT_CASE1_DEFENDER: 'Pabor ang Team B dahil may {agents} na nagsisilbing matibay na site anchor. Pinapayagan nito ang Team B na i-delay ang pag-atake at gumawa ng maayos na retake.',
    VERDICT_CASE2_ATTACKER: 'Pabor ang Team A dahil sa flexible na inisiasyon. Sa balanseng draf, madaling mapalabas ng Team A ang mga depensa ng Team B bago tuluyang pasukin ang site.',
    VERDICT_CASE2_DEFENDER: 'Ang Team B ay inaasahang maiiwan dahil sa masyadong agresibong draf (Double Duelist). Kung walang maayos na depensa sa mapang {map}, madali silang mapapalabas ng Team A.',
    VERDICT_CASE3_FAVORED: 'Pabor ang Team {favored} dahil sa mas mataas na kaalaman sa mapa. Ang average na panalo ng Team {favored} sa {map} ay mas mataas kumpara sa Team {lagging} sa rank {rank}.',
    VERDICT_CASE3_LAGGING: 'Ang Team {lagging} ay inaasahang maiiwan dahil ang average na panalo sa {map} ay hindi sapat kumpara sa draf ng Team {favored} sa rank {rank}.',
    SIDE_ANALYSIS_EMPTY: 'Wala pang napipiling Agent para sa {team}.',
    SIDE_ANALYSIS_ATTACK_STRONG: 'Sa kombinasyon ng <span class="text-[#F4D35E] font-bold">{agents}</span>, may malakas na <span class="text-[#F4D35E] font-bold">*entry explosion*</span> ang iyong koponan kapag nag-a-attack sa mapang <span class="text-[#F4D35E] font-bold">{map}</span> upang mapaatras ang depensa ng kalaban.',
    SIDE_ANALYSIS_ATTACK_WEAK: 'Ang iyong koponan ay posibleng mabara sa pag-atake dahil walang <span class="text-[#F4D35E] font-bold">Initiator</span> para sa paunang impormasyon. mapipilitan kayong makipag-shootout ng bulag.',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'May maayos na ritmo sa pag-atake ang iyong koponan at sapat na pag-usap sa mapang <span class="text-[#F4D35E] font-bold">{map}</span> upang isa-isahing linisin ang mga anggulo.',
    SIDE_ANALYSIS_DEFEND_STRONG: 'Napakatatag ng iyong depensa dahil kay <span class="text-[#F4D35E] font-bold">{agents}</span>. May kakayahan kayong mag-delay at mag-deny ng daanan kaya mapipilitan umikot ang kalaban.',
    SIDE_ANALYSIS_DEFEND_WEAK: 'Masyadong marupok ang depensa dahil walang anchor <span class="text-[#F4D35E] font-bold">Sentinel</span> sa mapang <span class="text-[#F4D35E] font-bold">{map}</span>. Mapipilitan kayong mag-defend sa labas ng site at aasa sa retake.',
    MICRO_REC_ROLE_GAP: 'Walang {role} sa iyong koponan. Ang pagpalit ng {oldAgent} kay {newAgent} ay napakahalaga upang harangan ang paningin ng kalaban sa {map} at madagdagan ng +{winrate}% ang tyansang manalo.',
    MICRO_REC_DOUBLE_DUELIST: 'Gumagamit ang Team B ng masyadong agresibong draf (Double Duelist) sa depensa sa mapang {map}. Ang pagpalit ng {oldAgent} kay {newAgent} (Sentinel) ay makakapagpatibay ng site anchor para mapigilan ang pasok ng kalaban.',
    MICRO_REC_MAP_SPECIFIC: 'Hindi maganda ang performance ni {oldAgent} sa {map} sa rank {rank}. Ang pagpalit kay {newAgent} ay magbibigay ng mas pare-parehong utility, na magpapataas sa simulasyon ng +{winrate}%.',
    MICRO_REC_EMPTY_SLOT: 'Ang pagpuno ng bakanteng slot kay {newAgent} ay magbibigay ng mas maayos na utility sa {map} sa rank {rank}, na magpapataas sa simulasyon ng +{winrate}%.',
    CHOOSE_MAP: 'Pumili ng Map',
    RANK_LOW: 'Iron - Silver',
    RANK_MID: 'Gold - Platinum',
    RANK_HIGH: 'Diamond - Radiant',
    SEARCH_AGENT_PLACEHOLDER: 'Maghanap ng agent...',
    SELECT_AGENT_FOR_TEAM: 'PUMILI NG AGENT PARA SA {team} (SLOT {slot})',
    CLOSE: 'Isara',
    SEARCH_AGENT: 'Maghanap ng agent...'
  },
  pt: {
    TOOL_VALORANT: 'Ferramentas do Valorant',
    AIM_SETTINGS: 'Mira & Configurações',
    AIM_TRAINER: 'Treino de Mira',
    PROFILE: 'Perfil',
    CROSSHAIR_BUILDER: 'Criador de Mira',
    SENS_CONVERTER: 'Conversor de Sensibilidade',
    SENS_FINDER: 'Buscador de Sensibilidade (PSA)',
    TACTICAL_TIER_LIST: 'Lista de Tier Tática',
    DRAFT_SIMULATOR: 'Simulador de Draft',
    ARMORY_HUB: 'Coleção',
    STRATEGY_BOARD: 'Quadro de Estratégias',
    TACTICAL_ANALYST_PLATFORM: 'PLATAFORMA DE ANÁLISE TÁTICA',
    SELECT_MAP_PLAN: 'Selecione um Mapa para Planejar',
    SEARCH_MAP: 'Buscar mapa...',
    ACTIVE_MAPS: 'Mapas Ativos',
    CUSTOM_MAPS: 'Mapas Personalizados',
    ALL_MAPS: 'Todos os Mapas',
    SIGN_IN_REGISTER: 'Entrar / Registrar-se',
    LOG_OUT: 'Sair',
    BACK_TO_HOME: 'Voltar ao Início',
    SWAP_SIDES: 'Inverter Lados',
    RESET_ALL: 'Redefinir Tudo',
    SIMULATE: 'Simular 10.000x',
    SIMULATING: 'Simulando...',
    SELECT_MAP: 'Selecionar Mapa',
    SKILL_BRACKET: 'Faixa de Habilidade',
    MATCH_ANALYST_FORECAST: 'Mecanismo Monte Carlo de Previsão de Partidas',
    ACTIVE_COMBAT_ZONE: 'Zona de Combate Ativa',
    MATCH_ANALYSIS_PROJECTION: 'Projeção de Análise da Partida',
    PROYEKSI_ANALISIS: 'Projeção de Análise de Partida',
    DETAILED_DUAL_SIDE_ANALYSIS: 'Análise Detalhada dos Dois Lados',
    EVALUASI_FASE_MENYERANG: 'Avaliação da Fase de Ataque',
    EVALUASI_FASE_BERTAHAN: 'Avaliação da Fase de Defesa',
    TEAM_A_ATTACKING: 'Time A Atacando',
    TEAM_B_ATTACKING: 'Time B Atacando',
    TEAM_A_DEFENDING: 'Time A Defendendo',
    TEAM_B_DEFENDING: 'Time B Defendendo',
    LIHAT_EVALUASI_TAKTIS: 'Ver Avaliação Tática',
    AUTO_RECOMMENDATION_ENGINE: 'Mecanismo de Recomendação Automática',
    ROLE_BALANCE_CHECK: 'Verificação de Equilíbrio de Funções',
    DETECTED_SYNERGIES: 'Sinergias Detectadas',
    COUNTERED_BY_OPPONENT: 'Anulado pelo Adversário',
    
    CHOOSE_5_AGENTS: 'Selecione 5 agentes para cada equipe e execute a simulação da partida.',
    REC_ENGINE_BANNER: 'MECANISMO DE RECOMENDAÇÃO AUTOMÁTICA',
    REC_INPUT_SMOKE: 'Insira um Smoke / Controlador para completar a base estratégica.',
    REC_GANTI: 'SUBSTITUIR',
    REC_RECOMMENDED_INPUT: 'ENTRADA RECOMENDADA',
    REC_DRAFT: 'SELECIONAR',
    EMPTY: 'VAZIO',
    HAPUS: 'Remover',
    SCAN_STEP1: 'AVALIANDO DADOS DE COMPOSIÇÃO DE FUNÇÕES...',
    SCAN_STEP2: 'ANALISANDO SINERGIAS E ANULAÇÕES...',
    SCAN_STEP3: 'CALCULANDO 10.000 DISTRIBUIÇÕES MATRICIAIS...',
    SCAN_STEP4: 'SIMULANDO CENÁRIOS DE PARTIDA...',
    VERDICT_TITLE_STRENGTH: 'PRINCIPAL FORÇA DO {team}',
    VERDICT_TITLE_WEAKNESS: 'PRINCIPAL FRAQUEZA DO {team}',
    VERDICT_CASE1_ATTACKER: 'O Time A deve enfrentar dificuldades devido à falta de um Sentinela para garantir o pós-plant. Mesmo se o Time A invadir o spike site, estará extremamente vulnerável a uma retomada (retake) coordenada da defesa do Time B.',
    VERDICT_CASE1_DEFENDER: 'O Time B está em vantagem por contar com {agents} atuando como âncoras sólidas do spike site. Isso permite ao Time B atrasar as entradas e executar retomadas coordenadas.',
    VERDICT_CASE2_ATTACKER: 'O Time A é favorito por sua alta flexibilidade de iniciação. Com uma seleção equilibrada, o Time A pode facilmente gastar os recursos defensivos do Time B antes de executar uma entrada massiva.',
    VERDICT_CASE2_DEFENDER: 'O Time B deve ficar atrás devido a uma seleção defensiva agressiva demais (Duplo Duelista). Sem âncoras passivas no mapa {map}, o Time B será facilmente atraído para fora e ditado pelas rotações táticas do Time A.',
    VERDICT_CASE3_FAVORED: 'O Time {favored} é favorito puramente por causa do domínio de mapa individual significativamente maior. A taxa média de vitória dos agentes selecionados do Time {favored} em {map} supera de longe a base do Time {lagging} no rank {rank}.',
    VERDICT_CASE3_LAGGING: 'O Time {lagging} deve ficar atrás porque a taxa média de vitória dos agentes selecionados em {map} é menos otimizada em comparação com a seleção do Time {favored} no rank {rank}.',
    SIDE_ANALYSIS_EMPTY: 'Nenhum agente selecionado para o {team} ainda.',
    SIDE_ANALYSIS_ATTACK_STRONG: 'Com a combinação de execução de <span class="text-[#F4D35E] font-bold">{agents}</span>, seu time tem uma força de entrada (<span class="text-[#F4D35E] font-bold">*entry explosion*</span>) muito alta no ataque no mapa <span class="text-[#F4D35E] font-bold">{map}</span>. Sua iniciação inicial é forte o suficiente para forçar a defesa inimiga a recuar.',
    SIDE_ANALYSIS_ATTACK_WEAK: 'Seu time deve enfrentar dificuldades no ataque devido à falta de um <span class="text-[#F4D35E] font-bold">Iniciador</span> para coletar informações. Você será forçado a duelos 1v1 às cegas, sem detecção de área prévia.',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'Seu time tem um ritmo de ataque moderado com iniciações táticas proporcionais no mapa <span class="text-[#F4D35E] font-bold">{map}</span>, permitindo limpar os ângulos do spike site progressivamente.',
    SIDE_ANALYSIS_DEFEND_STRONG: 'Sua fase de defesa é muito sólida graças à presença de <span class="text-[#F4D35E] font-bold">{agents}</span>. Você tem excelentes capacidades de atrasar entradas (<span class="text-[#F4D35E] font-bold">*delay*</span>) e bloquear passagens, forçando os atacantes a perder tempo ou rotacionar.',
    SIDE_ANALYSIS_DEFEND_WEAK: 'Sua defesa estática é altamente frágil devido à falta de um <span class="text-[#F4D35E] font-bold">Sentinela</span> âncora no mapa <span class="text-[#F4D35E] font-bold">{map}</span>. Você será forçado a jogar recuado fora do site e dependerá muito de retomadas (<span class="text-[#F4D35E] font-bold">*retake*</span>) coordenadas de alto risco.',
    MICRO_REC_ROLE_GAP: 'Sua composição de equipe atualmente não tem {role}. Substituir {oldAgent} por {newAgent} é crucial para bloquear as linhas de visão inimigas no mapa {map} e aumentar a taxa de vitória em +{winrate}%.',
    MICRO_REC_DOUBLE_DUELIST: 'O Time B está usando uma composição defensiva agressiva demais (Duplo Duelista) no mapa {map}. Substituir {oldAgent} por {newAgent} (Sentinela) garantirá uma âncora de site muito mais firme para impedir a penetração inimiga.',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent} tem estatísticas de desempenho abaixo do ideal no mapa {map} no rank {rank}. Substituí-lo por {newAgent} proporciona uma eficiência de utilitários mais consistente, aumentando a simulação projetada em +{winrate}%.',
    MICRO_REC_EMPTY_SLOT: 'Preencher a vaga aberta com {newAgent} proporciona uma eficiência de utilitários mais consistente no mapa {map} no rank {rank}, aumentando a simulação projetada em +{winrate}%.',
    CHOOSE_MAP: 'Escolha o Mapa',
    RANK_LOW: 'Iron - Silver',
    RANK_MID: 'Gold - Platinum',
    RANK_HIGH: 'Diamante - Radiante',
    SEARCH_AGENT_PLACEHOLDER: 'Buscar agente...',
    SELECT_AGENT_FOR_TEAM: 'SELECIONE UM AGENTE PARA O {team} (ESPAÇO {slot})',
    CLOSE: 'Fechar',
    SEARCH_AGENT: 'Buscar agente...'
  },
  tr: {
    TOOL_VALORANT: 'Valorant Araçları',
    AIM_SETTINGS: 'Nişan & Ayarlar',
    AIM_TRAINER: 'Nişan Eğitmeni',
    PROFILE: 'Profil',
    CROSSHAIR_BUILDER: 'Nişangah Oluşturucu',
    SENS_CONVERTER: 'Hassasiyet Dönüştürücü',
    SENS_FINDER: 'Hassasiyet Bulucu (PSA)',
    TACTICAL_TIER_LIST: 'Taktiksel Tier Listesi',
    DRAFT_SIMULATOR: 'Seçim Simülatörü',
    ARMORY_HUB: 'Koleksiyon',
    STRATEGY_BOARD: 'Strateji Tahtası',
    TACTICAL_ANALYST_PLATFORM: 'TAKTİKSEL ANALİZ PLATFORMU',
    SELECT_MAP_PLAN: 'Strateji Planı için Harita Seç',
    SEARCH_MAP: 'Harita ara...',
    ACTIVE_MAPS: 'Aktif Haritalar',
    CUSTOM_MAPS: 'Özel Haritalar',
    ALL_MAPS: 'Tüm Haritalar',
    SIGN_IN_REGISTER: 'Giriş Yap / Kaydol',
    LOG_OUT: 'Çıkış Yap',
    BACK_TO_HOME: 'Ana Sayfaya Dön',
    SWAP_SIDES: 'Taraf Değiştir',
    RESET_ALL: 'Hepsini Sıfırla',
    SIMULATE: '10.000x Simüle Et',
    SIMULATING: 'Simüle ediliyor...',
    SELECT_MAP: 'Harita Seç',
    SKILL_BRACKET: 'Yetenek Grubu',
    MATCH_ANALYST_FORECAST: 'Monte Carlo Karşılaşma Tahmin Motoru',
    ACTIVE_COMBAT_ZONE: 'Aktif Savaş Bölgesi',
    MATCH_ANALYSIS_PROJECTION: 'Karşılaşma Analiz Projeksiyonu',
    PROYEKSI_ANALISIS: 'Karşılaşma Analiz Öngörüsü',
    DETAILED_DUAL_SIDE_ANALYSIS: 'Detaylı Çift Yönlü Analiz',
    EVALUASI_FASE_MENYERANG: 'Saldırı Aşaması Değerlendirmesi',
    EVALUASI_FASE_BERTAHAN: 'Savunma Aşaması Değerlendirmesi',
    TEAM_A_ATTACKING: 'A Takımı Saldırıyor',
    TEAM_B_ATTACKING: 'B Takımı Saldırıyor',
    TEAM_A_DEFENDING: 'A Takımı Savunuyor',
    TEAM_B_DEFENDING: 'B Takımı Savunuyor',
    LIHAT_EVALUASI_TAKTIS: 'Taktiksel Değerlendirmeyi Gör',
    AUTO_RECOMMENDATION_ENGINE: 'Otomatik Öneri Motoru',
    ROLE_BALANCE_CHECK: 'Rol Dengesi Kontrolü',
    DETECTED_SYNERGIES: 'Tespit Edilen Sinerjiler',
    COUNTERED_BY_OPPONENT: 'Rakip Tarafından Karşılananlar',
    
    CHOOSE_5_AGENTS: 'Her takım için 5 Temsilci seçin ve karşılaşma simülasyonunu çalıştırın.',
    REC_ENGINE_BANNER: 'OTOMATİK ÖNERİ MOTORU',
    REC_INPUT_SMOKE: 'Stratejik temeli tamamlamak için Duman / Kontrol Uzmanı ekleyin.',
    REC_GANTI: 'DEĞİŞTİR',
    REC_RECOMMENDED_INPUT: 'ÖNERİLEN GİRİŞ',
    REC_DRAFT: 'SEÇ',
    EMPTY: 'BOŞ',
    HAPUS: 'Kaldır',
    SCAN_STEP1: 'ROL BİLEŞİMİ VERİLERİ DEĞERLENDİRİLİYOR...',
    SCAN_STEP2: 'SİNERJİLER VE KARŞI SEÇİMLER ANALİZ EDİLİYOR...',
    SCAN_STEP3: '10.000 MATRİS DAĞILIMI HESAPLANIYOR...',
    SCAN_STEP4: 'KARŞILAŞMA SENARYOLARI SİMÜLE EDİLİYOR...',
    VERDICT_TITLE_STRENGTH: '{team} TAKIMININ ANA GÜCÜ',
    VERDICT_TITLE_WEAKNESS: '{team} TAKIMININ ANA ZAFİYETİ',
    VERDICT_CASE1_ATTACKER: 'A Takımı, spike kurulduktan sonra bölgeyi tutacak bir Gözcüye sahip olmadığı için zorlanabilir. Bölgeye girseler bile, B Takımı\'nın organize geri alım (retake) savunmasına karşı son derece savunmasız kalacaklardır.',
    VERDICT_CASE1_DEFENDER: 'B Takımı, sağlam bölge çapası görevi gören {agents} sayesinde avantajlıdır. Bu durum B Takımı\'nın girişleri geciktirmesini ve koordineli geri alımlar (retake) yapmasını sağlar.',
    VERDICT_CASE2_ATTACKER: 'A Takımı yüksek başlatma esnekliği sayesinde avantajlıdır. Dengeli bir seçimle A Takımı, büyük bir bölge infazı yapmadan önce B Takımı\'nın savunma yeteneklerini kolayca harcatabilir.',
    VERDICT_CASE2_DEFENDER: 'B Takımı, aşırı agresif savunma seçimi (Çift Düellocu) nedeniyle geride kalabilir. {map} haritasında pasif bölge tutucuları olmadan B Takımı kolayca kandırılıp A Takımı\'nın taktiksel rotasyonlarına boyun eğecektir.',
    VERDICT_CASE3_FAVORED: '{favored} Takımı, bireysel harita hakimiyetinin çok daha yüksek olması sebebiyle avantajlıdır. {favored} Takımı\'nın seçtiği temsilcilerin {map} haritasındaki ortalama kazanma oranı, {rank} düzeyinde {lagging} Takımı\'nın taban oranından çok daha yüksektir.',
    VERDICT_CASE3_LAGGING: '{lagging} Takımı, seçilen temsilcilerin {map} haritasındaki ortalama kazanma oranının {rank} düzeyinde {favored} Takımı\'nın seçimine göre daha düşük olması nedeniyle geride kalabilir.',
    SIDE_ANALYSIS_EMPTY: '{team} için henüz bir Temsilci seçilmedi.',
    SIDE_ANALYSIS_ATTACK_STRONG: '<span class="text-[#F4D35E] font-bold">{agents}</span> yetenek kombinasyonları sayesinde takımınız, <span class="text-[#F4D35E] font-bold">{map}</span> haritasındaki saldırı aşamasında çok yüksek bir giriş gücüne (<span class="text-[#F4D35E] font-bold">*entry explosion*</span>) sahip olur. Başlangıç hamleniz düşman savunmasını geri püskürtmek için son derece güçlüdür.',
    SIDE_ANALYSIS_ATTACK_WEAK: 'Takımınız, erken bilgi toplayacak bir <span class="text-[#F4D35E] font-bold">Öncü</span> bulunmadığı için saldırıda zorlanabilir. Alan tespiti olmadan körü körüne 1v1 düellolara girmek zorunda kalacaksınız.',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'Takımınız, <span class="text-[#F4D35E] font-bold">{map}</span> haritasında ölçülü bir saldırı temposuna ve dengeli taktiksel başlatmalara sahiptir, bu da bölge açılarının kademeli olarak temizlenmesini sağlar.',
    SIDE_ANALYSIS_DEFEND_STRONG: '<span class="text-[#F4D35E] font-bold">{agents}</span> varlığı sayesinde savunma aşamanız oldukça sağlamdır. Harika bir giriş geciktirme (<span class="text-[#F4D35E] font-bold">*delay*</span>) ve dar geçit kapatma yeteneğiniz vardır, bu da saldıranları zaman kaybetmeye veya haritada dönmeye zorlar.',
    SIDE_ANALYSIS_DEFEND_WEAK: '<span class="text-[#F4D35E] font-bold">{map}</span> haritasında çapası olacak bir <span class="text-[#F4D35E] font-bold">Gözcü</span> bulunmadığı için savunmanız oldukça zayıftır. Bölgenin uzağında defansif oynamak zorunda kalırsınız ve yüksek riskli geri alım (<span class="text-[#F4D35E] font-bold">*retake*</span>) koordinasyonlarına aşırı bağımlı olursunuz.',
    MICRO_REC_ROLE_GAP: 'Takım bileşiminizde şu anda {role} rolü eksik. Düşmanın görüş hatlarını kapatmak ve kazanma oranını +%{winrate} artırmak için {oldAgent} yerine {newAgent} seçmek kritik önem taşır.',
    MICRO_REC_DOUBLE_DUELIST: 'B Takımı şu anda {map} haritasında savunma için fazla agresif bir kadro (Çift Düellocu) kullanıyor. {oldAgent} yerine {newAgent} (Gözcü) seçmek, düşman sızmasını durdurmak için çok daha sağlam bir bölge çapası sağlayacaktır.',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent}, {rank} düzeyinde {map} haritasında ideal olmayan performans istatistiklerine sahip. Onun yerine {newAgent} seçmek daha tutarlı bir yetenek verimliliği sağlayarak projeksiyon simülasyonunu +%{winrate} artırır.',
    MICRO_REC_EMPTY_SLOT: 'Boş alanı {newAgent} ile doldurmak, {rank} düzeyinde {map} haritasında daha tutarlı bir yetenek verimliliği sağlayarak projeksiyon simülasyonunu +%{winrate} artırır.',
    CHOOSE_MAP: 'Harita Seç',
    RANK_LOW: 'Demir - Gümüş',
    RANK_MID: 'Altın - Platin',
    RANK_HIGH: 'Elmas - Işıldayan',
    SEARCH_AGENT_PLACEHOLDER: 'Temsilci ara...',
    SELECT_AGENT_FOR_TEAM: '{team} İÇİN TEMSİLCİ SEÇ (ALAN {slot})',
    CLOSE: 'Kapat',
    SEARCH_AGENT: 'Temsilci ara...'
  },
  ko: {
    TOOL_VALORANT: '발로란트 도구',
    AIM_SETTINGS: '조준 & 설정',
    AIM_TRAINER: '에임 트레이너',
    PROFILE: '프로필',
    CROSSHAIR_BUILDER: '조준선 생성기',
    SENS_CONVERTER: '감도 변환기',
    SENS_FINDER: '감도 탐색기 (PSA)',
    TACTICAL_TIER_LIST: '전술 티어 리스트',
    DRAFT_SIMULATOR: '드래프트 시뮬레이터',
    ARMORY_HUB: '컬렉션',
    STRATEGY_BOARD: '전술 보드',
    TACTICAL_ANALYST_PLATFORM: '전술 분석 플랫폼',
    SELECT_MAP_PLAN: '전략을 계획할 맵 선택',
    SEARCH_MAP: '맵 검색...',
    ACTIVE_MAPS: '활성 맵 목록',
    CUSTOM_MAPS: '커스텀 맵 목록',
    ALL_MAPS: '모든 맵',
    SIGN_IN_REGISTER: '로그인 / 회원가입',
    LOG_OUT: '로그아웃',
    BACK_TO_HOME: '홈으로 돌아가기',
    SWAP_SIDES: '진영 교체',
    RESET_ALL: '모두 초기화',
    SIMULATE: '10,000회 시뮬레이션',
    SIMULATING: '시뮬레이션 중...',
    SELECT_MAP: '맵 선택',
    SKILL_BRACKET: '실력 등급',
    MATCH_ANALYST_FORECAST: '몬테카를로 매치 결과 예측 엔진',
    ACTIVE_COMBAT_ZONE: '활성 전투 지역',
    MATCH_ANALYSIS_PROJECTION: '매치 분석 예측',
    PROYEKSI_ANALISIS: '매치 분석 예측',
    DETAILED_DUAL_SIDE_ANALYSIS: '상세 양진영 분석',
    EVALUASI_FASE_MENYERANG: '공격 단계 평가',
    EVALUASI_FASE_BERTAHAN: '수비 단계 평가',
    TEAM_A_ATTACKING: 'A 팀 공격',
    TEAM_B_ATTACKING: 'B 팀 공격',
    TEAM_A_DEFENDING: 'A 팀 수비',
    TEAM_B_DEFENDING: 'B 팀 수비',
    LIHAT_EVALUASI_TAKTIS: '전술 평가 확인',
    AUTO_RECOMMENDATION_ENGINE: '자동 추천 엔진',
    ROLE_BALANCE_CHECK: '역할 밸런스 체크',
    DETECTED_SYNERGIES: '감지된 시너지',
    COUNTERED_BY_OPPONENT: '상대방 카운터',
    
    CHOOSE_5_AGENTS: '각 팀당 5명의 요원을 선택하고 매치 시뮬레이션을 실행하세요.',
    REC_ENGINE_BANNER: '자동 추천 엔진',
    REC_INPUT_SMOKE: '전략적 기틀을 완성하기 위해 연막/컨트롤러 요원을 선택하세요.',
    REC_GANTI: '교체',
    REC_RECOMMENDED_INPUT: '추천 입력',
    REC_DRAFT: '선택',
    EMPTY: '비어 있음',
    HAPUS: '삭제',
    SCAN_STEP1: '역할군 조합 데이터 평가 중...',
    SCAN_STEP2: '시너지 및 카운터 픽 분석 중...',
    SCAN_STEP3: '10,000개의 행렬 분포 계산 중...',
    SCAN_STEP4: '매치 시나리오 시뮬레이션 중...',
    VERDICT_TITLE_STRENGTH: '{team}의 주요 강점',
    VERDICT_TITLE_WEAKNESS: '{team}의 주요 약점',
    VERDICT_CASE1_ATTACKER: 'A 팀은 스파이크 설치 후 사이트를 사수할 감시자가 없어 고전할 것으로 예상됩니다. 설령 A 팀이 사이트를 장악하더라도, B 팀의 유기적인 리테이크 수비에 매우 취약해질 것입니다.',
    VERDICT_CASE1_DEFENDER: 'B 팀은 든든한 사이트 앵커 역할을 하는 {agents} 덕분에 우세합니다. 이는 B 팀이 진입을 지연시키고 빈틈없는 리테이크를 실행할 수 있게 해줍니다.',
    VERDICT_CASE2_ATTACKER: 'A 팀은 높은 전술 시작 유연성 덕분에 우세합니다. 짜임새 있는 조합을 바탕으로 A 팀은 본격적인 사이트 진입 전에 B 팀의 수비 스킬을 쉽게 유도하여 낭비시킬 수 있습니다.',
    VERDICT_CASE2_DEFENDER: 'B 팀은 과도하게 공격적인 수비 조합(더블 타격대)으로 인해 고전할 것으로 예상됩니다. {map} 맵에서 단단한 수비 앵커가 없으면 B 팀은 쉽게 유인되어 A 팀의 로테이션 회전에 휘둘릴 것입니다.',
    VERDICT_CASE3_FAVORED: '{favored} 팀은 전적으로 뛰어난 개별 맵 숙련도 덕분에 우세합니다. {map} 맵에서 {favored} 팀 요원들의 평균 기본 승률은 {rank} 등급에서의 {lagging} 팀의 수치를 크게 웃돕니다.',
    VERDICT_CASE3_LAGGING: '{lagging} 팀은 {map} 맵에서 선택한 요원들의 평균 승률이 {rank} 등급에서의 {favored} 팀 조합 대비 다소 떨어지기 때문에 열세로 예상됩니다.',
    SIDE_ANALYSIS_EMPTY: '{team}에 선택된 요원이 아직 없습니다.',
    SIDE_ANALYSIS_ATTACK_STRONG: '<span class="text-[#F4D35E] font-bold">{agents}</span>의 돌파 조합을 바탕으로, 귀하의 팀은 <span class="text-[#F4D35E] font-bold">{map}</span> 수비진을 무력화할 수 있는 강력한 사이트 진입 파괴력(<span class="text-[#F4D35E] font-bold">*entry explosion*</span>)을 가집니다. 적의 방어선을 밀어붙이는 개시 능력이 매우 뛰어납니다.',
    SIDE_ANALYSIS_ATTACK_WEAK: '귀하의 팀은 정보를 수집할 <span class="text-[#F4D35E] font-bold">척후대</span>가 없어 공격 시 진입로 개척에 큰 어려움을 겪을 수 있습니다. 시야 및 감지 스킬 지원 없이 위험한 1대1 교전을 강요당하게 됩니다.',
    SIDE_ANALYSIS_ATTACK_BALANCED: '귀하의 팀은 <span class="text-[#F4D35E] font-bold">{map}</span> 맵에서 적절한 속도의 공격 템포와 체계적인 전술 개시 능력을 가집니다. 이를 통해 사이트 구석구석을 단계적으로 클리어하며 조율해 나갈 수 있습니다.',
    SIDE_ANALYSIS_DEFEND_STRONG: '<span class="text-[#F4D35E] font-bold">{agents}</span> 덕분에 귀하의 팀 수비 진형은 매우 견고합니다. 탁월한 진입 지연(<span class="text-[#F4D35E] font-bold">*delay*</span>) 및 좁은 길 차단 스킬을 보유하고 있어, 적의 공격 속도를 늦추거나 먼 길로 우회하게 만듭니다.',
    SIDE_ANALYSIS_DEFEND_WEAK: '<span class="text-[#F4D35E] font-bold">{map}</span> 맵에서 버텨줄 감시 포지션의 <span class="text-[#F4D35E] font-bold">감시자</span>가 없어 우직한 수비 유지가 어렵습니다. 사이트 뒷선까지 물러서서 막아야 하며, 성공 확률이 낮은 리테이크(<span class="text-[#F4D35E] font-bold">*retake*</span>) 운영에 전적으로 의존해야 합니다.',
    MICRO_REC_ROLE_GAP: '현재 팀 조합에 {role} 요원이 없습니다. {map} 맵에서 상대의 시야 각도를 차단하고 아군 승률을 +{winrate}% 높이기 위해 {oldAgent} 요원을 {newAgent} 요원으로 교체하는 것이 시급합니다.',
    MICRO_REC_DOUBLE_DUELIST: '현재 B 팀은 수비 포지션임에도 불구하고 {map} 맵에서 지나치게 공격적인 조합(더블 타격대)을 사용 중입니다. {oldAgent} 요원을 {newAgent} 요원(감시자)으로 교체하면 적의 진입을 막아낼 견고한 사이트 앵커를 확보할 수 있습니다.',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent} 요원은 {rank} 등급의 {map} 맵에서 다소 불리한 지표를 보이고 있습니다. {newAgent} 요원으로 변경하면 더 안정적으로 스킬을 운용할 수 있어 아군의 가상 승률을 +{winrate}% 더 끌어올릴 수 있습니다.',
    MICRO_REC_EMPTY_SLOT: '비어 있는 슬롯을 {newAgent} 요원으로 채우면 {rank} 등급의 {map} 맵에서 스킬 효율을 향상시켜 아군의 승리 가상치를 +{winrate}% 더 끌어올릴 수 있습니다.',
    CHOOSE_MAP: '맵 선택',
    RANK_LOW: '아이언 - 실버',
    RANK_MID: '골드 - 플래티넘',
    RANK_HIGH: '다이아몬드 - 레디언트',
    SEARCH_AGENT_PLACEHOLDER: '요원 검색...',
    SELECT_AGENT_FOR_TEAM: '{team} 요원 선택 (슬롯 {slot})',
    CLOSE: '닫기',
    SEARCH_AGENT: '요원 검색...'
  },
  ru: {
    TOOL_VALORANT: 'Инструменты Valorant',
    AIM_SETTINGS: 'Аим и Настройки',
    AIM_TRAINER: 'Тренажёр прицеливания',
    PROFILE: 'Профиль',
    CROSSHAIR_BUILDER: 'Конструктор прицела',
    SENS_CONVERTER: 'Конвертер чувствительности',
    SENS_FINDER: 'Поиск чувствительности (PSA)',
    TACTICAL_TIER_LIST: 'Тактический тир-лист',
    DRAFT_SIMULATOR: 'Симулятор пиков',
    ARMORY_HUB: 'Коллекция',
    STRATEGY_BOARD: 'Тактическая доска',
    TACTICAL_ANALYST_PLATFORM: 'ТАКТИЧЕСКАЯ АНАЛИТИЧЕСКАЯ ПЛАТФОРМА',
    SELECT_MAP_PLAN: 'Выберите карту для планирования стратегии',
    SEARCH_MAP: 'Поиск карты...',
    ACTIVE_MAPS: 'Активные карты',
    CUSTOM_MAPS: 'Пользовательские карты',
    ALL_MAPS: 'Все карты',
    SIGN_IN_REGISTER: 'Войти / Зарегистрироваться',
    LOG_OUT: 'Выйти',
    BACK_TO_HOME: 'На главную',
    SWAP_SIDES: 'Поменяться сторонами',
    RESET_ALL: 'Сбросить все',
    SIMULATE: 'Симулировать 10 000 раз',
    SIMULATING: 'Симуляция...',
    SELECT_MAP: 'Выбрать карту',
    SKILL_BRACKET: 'Уровень навыка',
    MATCH_ANALYST_FORECAST: 'Прогноз результатов матчей методом Монте-Карло',
    ACTIVE_COMBAT_ZONE: 'Активная зона боевых действий',
    MATCH_ANALYSIS_PROJECTION: 'Прогноз анализа матча',
    PROYEKSI_ANALISIS: 'Аналитический прогноз матча',
    DETAILED_DUAL_SIDE_ANALYSIS: 'Детальный двусторонний анализ',
    EVALUASI_FASE_MENYERANG: 'Оценка фазы атаки',
    EVALUASI_FASE_BERTAHAN: 'Оценка фазы защиты',
    TEAM_A_ATTACKING: 'Атакует Команда А',
    TEAM_B_ATTACKING: 'Атакует Команда Б',
    TEAM_A_DEFENDING: 'Защищается Команда А',
    TEAM_B_DEFENDING: 'Защищается Команда Б',
    LIHAT_EVALUASI_TAKTIS: 'Посмотреть тактическую оценку',
    AUTO_RECOMMENDATION_ENGINE: 'Система авторекомендаций',
    ROLE_BALANCE_CHECK: 'Проверка баланса ролей',
    DETECTED_SYNERGIES: 'Обнаруженная синергия',
    COUNTERED_BY_OPPONENT: 'Законтрено противником',
    
    CHOOSE_5_AGENTS: 'Выберите по 5 агентов для каждой команды и запустите симуляцию матча.',
    REC_ENGINE_BANNER: 'Система авторекомендаций',
    REC_INPUT_SMOKE: 'Добавьте дым / специалиста контроля для завершения тактической базы.',
    REC_GANTI: 'ЗАМЕНИТЬ',
    REC_RECOMMENDED_INPUT: 'РЕКОМЕНДУЕМЫЙ ВВОД',
    REC_DRAFT: 'ПИКНУТЬ',
    EMPTY: 'ПУСТО',
    HAPUS: 'Удалить',
    SCAN_STEP1: 'ОЦЕНКА ДАННЫХ СОСТАВА РОЛЕЙ...',
    SCAN_STEP2: 'АНАЛИЗ СИНЕРГИИ И КОНТРПИКОВ...',
    SCAN_STEP3: 'РАСЧЕТ 10 000 МАТРИЧНЫХ РАСПРЕДЕЛЕНИЙ...',
    SCAN_STEP4: 'МОДЕЛИРОВАНИЕ СЦЕНАРИЕВ МАТЧА...',
    VERDICT_TITLE_STRENGTH: 'ГЛАВНОЕ ПРЕИМУЩЕСТВО {team}',
    VERDICT_TITLE_WEAKNESS: 'ГЛАВНЫЙ НЕДОСТАТОК {team}',
    VERDICT_CASE1_ATTACKER: 'Команде А прогнозируют трудности из-за отсутствия Стража для удержания позиций после установки спайка. Даже если Команда А займет точку, они будут крайне уязвимы для скоординированного ретейка со стороны Команды Б.',
    VERDICT_CASE1_DEFENDER: 'Команда Б имеет преимущество благодаря наличию {agents}, выступающих в роли надежных защитников точек. Это позволяет Команде Б сдерживать натиск и проводить слаженные ретейки.',
    VERDICT_CASE2_ATTACKER: 'Команда А фаворит благодаря высокой гибкости инициации. Имея сбалансированный пик, Команда А может легко выманить защитные утилиты Команды Б перед массированным штурмом точки.',
    VERDICT_CASE2_DEFENDER: 'Команда Б прогнозируют отставание из-за слишком агрессивного пика обороны (два Дуэлянта). Без надежной пассивной защиты на карте {map} Команда Б будет легко выманиваться и подстраиваться под ротации Команды А.',
    VERDICT_CASE3_FAVORED: 'Команда {favored} имеет преимущество исключительно благодаря более высокому уровню освоения карты. Средний показатель побед выбранных агентов Команды {favored} на карте {map} значительно превышает базовый уровень Команды {lagging} на ранге {rank}.',
    VERDICT_CASE3_LAGGING: 'Команде {lagging} прогнозируют отставание, так как средний базовый процент побед выбранных агентов на карте {map} менее оптимален по сравнению с пиком Команды {favored} на ранге {rank}.',
    SIDE_ANALYSIS_EMPTY: 'Для {team} еще не выбраны агенты.',
    SIDE_ANALYSIS_ATTACK_STRONG: 'Благодаря действиям <span class="text-[#F4D35E] font-bold">{agents}</span> ваша команда обладает высокой пробивной силой (<span class="text-[#F4D35E] font-bold">*entry explosion*</span>) в фазе атаки на карте <span class="text-[#F4D35E] font-bold">{map}</span>. Ваша инициация достаточно сильна, чтобы заставить врага отступить.',
    SIDE_ANALYSIS_ATTACK_WEAK: 'Ваша команда может столкнуться с трудностями при атаке из-за отсутствия <span class="text-[#F4D35E] font-bold">Зачинщика</span> для сбора информации. Вы будете вынуждены идти на дуэли вслепую без предварительного сканирования зон.',
    SIDE_ANALYSIS_ATTACK_BALANCED: 'У вашей команды взвешенный темп атаки с пропорциональной тактической инициацией на карте <span class="text-[#F4D35E] font-bold">{map}</span>, что позволяет постепенно зачищать углы на точке.',
    SIDE_ANALYSIS_DEFEND_STRONG: 'Ваша фаза защиты очень надежна благодаря присутствию <span class="text-[#F4D35E] font-bold">{agents}</span>. У вас отличные возможности для задержки врага (<span class="text-[#F4D35E] font-bold">*delay*</span>) и блокировки проходов, что вынуждает атакующих терять время.',
    SIDE_ANALYSIS_DEFEND_WEAK: 'Ваша статическая оборона очень уязвима из-за отсутствия <span class="text-[#F4D35E] font-bold">Стража</span> на карте <span class="text-[#F4D35E] font-bold">{map}</span>. Вам придется играть глубоко позади точки и сильно полагаться на рискованные ретейки (<span class="text-[#F4D35E] font-bold">*retake*</span>).',
    MICRO_REC_ROLE_GAP: 'В вашем составе в данный момент нет класса {role}. Замена {oldAgent} на {newAgent} критически важна, чтобы закрыть обзор врагу на карте {map} и повысить винрейт на +{winrate}%.',
    MICRO_REC_DOUBLE_DUELIST: 'Команда Б в данный момент использует слишком агрессивный состав обороны (два Дуэлянта) на карте {map}. Замена {oldAgent} на {newAgent} (Страж) обеспечит более надежного защитника точки для отражения атак.',
    MICRO_REC_MAP_SPECIFIC: '{oldAgent} имеет субоптимальные показатели эффективности на карте {map} на ранге {rank}. Замена на {newAgent} обеспечит более стабильную пользу утилит, повысив прогноз симуляции на +{winrate}%.',
    MICRO_REC_EMPTY_SLOT: 'Заполнение пустого слота агентом {newAgent} обеспечит более стабильную пользу утилит на карте {map} на ранге {rank}, повысив прогноз симуляции на +{winrate}%.',
    CHOOSE_MAP: 'Выбрать карту',
    RANK_LOW: 'Железо - Серебро',
    RANK_MID: 'Золото - Платина',
    RANK_HIGH: 'Алмаз - Радиант',
    SEARCH_AGENT_PLACEHOLDER: 'Поиск агента...',
    SELECT_AGENT_FOR_TEAM: 'ВЫБЕРИТЕ АГЕНТА ДЛЯ {team} (СЛОТ {slot})',
    CLOSE: 'Закрыть',
    SEARCH_AGENT: 'Поиск агента...'
  },
  zh: {
    TOOL_VALORANT: 'Valorant 工具箱',
    AIM_SETTINGS: '瞄准与设置',
    AIM_TRAINER: '瞄准训练器',
    PROFILE: '个人资料',
    CROSSHAIR_BUILDER: '准星生成器',
    SENS_CONVERTER: '灵敏度转换器',
    SENS_FINDER: '灵敏度定位器 (PSA)',
    TACTICAL_TIER_LIST: '战术梯度表',
    DRAFT_SIMULATOR: '阵容模拟器',
    ARMORY_HUB: '收藏',
    STRATEGY_BOARD: '战术策划板',
    TACTICAL_ANALYST_PLATFORM: '战术分析平台',
    SELECT_MAP_PLAN: '选择地图规划战术',
    SEARCH_MAP: '搜索地图...',
    ACTIVE_MAPS: '现役地图',
    CUSTOM_MAPS: '自定义地图',
    ALL_MAPS: '所有地图',
    SIGN_IN_REGISTER: '登录 / 注册',
    LOG_OUT: '退出登录',
    BACK_TO_HOME: '返回首页',
    SWAP_SIDES: '交换阵容',
    RESET_ALL: '全部重置',
    SIMULATE: '进行 10,000 次模拟',
    SIMULATING: '正在模拟...',
    SELECT_MAP: '选择地图',
    SKILL_BRACKET: '段位水平',
    MATCH_ANALYST_FORECAST: '蒙特卡罗比赛结果预测引擎',
    ACTIVE_COMBAT_ZONE: '活跃战斗区域',
    MATCH_ANALYSIS_PROJECTION: '比赛分析预测',
    PROYEKSI_ANALISIS: '比赛分析预测',
    DETAILED_DUAL_SIDE_ANALYSIS: '双侧深度战术分析',
    EVALUASI_FASE_MENYERANG: '进攻端表现评估',
    EVALUASI_FASE_BERTAHAN: '防守端表现评估',
    TEAM_A_ATTACKING: '队伍 A 进攻',
    TEAM_B_ATTACKING: '队伍 B 进攻',
    TEAM_A_DEFENDING: '队伍 A 防守',
    TEAM_B_DEFENDING: '队伍 B 防守',
    LIHAT_EVALUASI_TAKTIS: '查看战术深度评测',
    AUTO_RECOMMENDATION_ENGINE: '智能自动推荐系统',
    ROLE_BALANCE_CHECK: '阵容定位均衡度检查',
    DETECTED_SYNERGIES: '已激活团队默契',
    COUNTERED_BY_OPPONENT: '受到对手战术克制',
    
    CHOOSE_5_AGENTS: '为两支队伍各选择5位特工并运行比赛模拟。',
    REC_ENGINE_BANNER: '智能自动推荐系统',
    REC_INPUT_SMOKE: '选入控场者（烟位）以构建基础战术系统。',
    REC_GANTI: '替换',
    REC_RECOMMENDED_INPUT: '推荐选入',
    REC_DRAFT: '选入',
    EMPTY: '待选',
    HAPUS: '移除',
    SCAN_STEP1: '评估阵容定位构成数据...',
    SCAN_STEP2: '分析团队默契与对手克制关系...',
    SCAN_STEP3: '计算 10,000 次矩阵分布概率...',
    SCAN_STEP4: '运行对局场景博弈模拟...',
    VERDICT_TITLE_STRENGTH: '{team} 的主要战术优势',
    VERDICT_TITLE_WEAKNESS: '{team} 的主要战术劣势',
    VERDICT_CASE1_ATTACKER: '队伍 A 预计会因为缺乏哨卫来进行下包后防守而陷入苦战。即便成功进入包点，他们也将极易受到队伍 B 层层布防的回防夹击。',
    VERDICT_CASE1_DEFENDER: '队伍 B 占得先机，因为他们拥有特工 {agents} 作为坚实的包点锚点。这使得队伍 B 能够拖延对手的进攻并执行极其流畅的回防配合。',
    VERDICT_CASE2_ATTACKER: '队伍 A 凭借极高的协同起手灵活性占据上风。拥有均衡的阵容，队伍 A 可以在实施包点总攻前，轻松骗出队伍 B 的防守道具。',
    VERDICT_CASE2_DEFENDER: '队伍 B 预计会因为防守阵容过于激进（双决斗者）而落后。在 {map} 地图上缺乏稳固的阵地守卫，队伍 B 将极易被对手骗出点外，被队伍 A 的战术转场牵着鼻子走。',
    VERDICT_CASE3_FAVORED: '队伍 {favored} 占优纯粹是因为其显著胜出一筹的个人地图熟练度。队伍 {favored} 的特工在 {map} 地图上的平均基础胜率在 {rank} 段位中远超队伍 {lagging} 的基准线。',
    VERDICT_CASE3_LAGGING: '队伍 {lagging} 预计将处于劣势，因为所选特工在 {map} 地图上的平均基础胜率相比队伍 {favored} 在 {rank} 的表现显得不够理想。',
    SIDE_ANALYSIS_EMPTY: '尚未为 {team} 选择特工。',
    SIDE_ANALYSIS_ATTACK_STRONG: '得益于特工 <span class="text-[#F4D35E] font-bold">{agents}</span> 的突进配合，您的队伍在地图 <span class="text-[#F4D35E] font-bold">{map}</span> 的进攻阶段具备极高的突破爆发力（<span class="text-[#F4D35E] font-bold">*entry explosion*</span>）。您的第一波协同开团能瞬间逼退敌方的防线。',
    SIDE_ANALYSIS_ATTACK_WEAK: '您的队伍预计会在进攻时遭遇严重的信息断流，因为缺少 <span class="text-[#F4D35E] font-bold">先锋</span> 特工来收集前置信息。在缺乏探点技能的情况下，您将被迫进行极其被动的盲区一对一干拉决斗。',
    SIDE_ANALYSIS_ATTACK_BALANCED: '您的队伍在地图 <span class="text-[#F4D35E] font-bold">{map}</span> 上拥有合理的进攻节奏与均衡的战术试探，可支持团队稳扎稳打地逐步清空包点死角。',
    SIDE_ANALYSIS_DEFEND_STRONG: '得益于特工 <span class="text-[#F4D35E] font-bold">{agents}</span> 的存在，您的防守端极其坚固。您具备极佳的阻滞敌方进点（<span class="text-[#F4D35E] font-bold">*delay*</span>）与路口封堵控制能力，能迫使对手浪费时间或被迫绕道远转。',
    SIDE_ANALYSIS_DEFEND_WEAK: '您的固定阵地防线在地图 <span class="text-[#F4D35E] font-bold">{map}</span> 上显得十分薄弱，因为缺乏可守点的 <span class="text-[#F4D35E] font-bold">哨卫</span> 作为支柱。您将被迫在点外深处打防守放点，极度依赖高风险的回防协同（<span class="text-[#F4D35E] font-bold">*retake*</span>）。',
    MICRO_REC_ROLE_GAP: '您当前的阵容中缺少定位：{role}。将 {oldAgent} 替换为 {newAgent} 对于封锁地图 {map} 上敌人的视野至关重要，能让您的胜率提高 +{winrate}%。',
    MICRO_REC_DOUBLE_DUELIST: '队伍 B 当前在地图 {map} 的防守端使用了过于激进的阵容（双决斗者）。将 {oldAgent} 替换为 {newAgent}（哨卫）将为您的队伍提供更稳固的包点守卫以抵御对手强突。',
    MICRO_REC_MAP_SPECIFIC: '特工 {oldAgent} 在段位为 {rank} 的地图 {map} 上的实战表现数据不太理想。将其替换为 {newAgent} 能发挥更稳定的技能效率，从而提升对局模拟胜率 +{winrate}%。',
    MICRO_REC_EMPTY_SLOT: '用特工 {newAgent} 填补当前阵容空缺，可以在段位为 {rank} 的地图 {map} 上提供更稳定的技能收益，从而提升对局模拟胜率 +{winrate}%。',
    CHOOSE_MAP: '选择地图',
    RANK_LOW: '黑铁 - 白银',
    RANK_MID: '黄金 - 白金',
    RANK_HIGH: '钻石 - 耀光',
    SEARCH_AGENT_PLACEHOLDER: '搜索特工名称...',
    SELECT_AGENT_FOR_TEAM: '为 {team} 选择特工（位置 {slot}）',
    CLOSE: '关闭',
    SEARCH_AGENT: '搜索特工...'
  }
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, replacements?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const stored = localStorage.getItem('valportal_lang');
    return (stored as LanguageCode) || 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('valportal_lang', lang);
  };

  const t = (key: string, replacements?: Record<string, string>): string => {
    const dict = TRANSLATIONS[language] || TRANSLATIONS.en;
    let text = dict[key] || TRANSLATIONS.en[key] || key;
    if (replacements) {
      Object.entries(replacements).forEach(([placeholder, val]) => {
        text = text.replace(new RegExp(`{${placeholder}}`, 'g'), val);
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
